trigger:
- main

pool:
  name: devops  # Self-hosted agent

steps:
- checkout: self

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Install backend dependencies
- script: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

# Run SonarScanner CLI
- script: |
    sonar-scanner -Dsonar.projectKey=my-expense-app `
                  -Dsonar.sources=backend,frontend `
                  -Dsonar.host.url=http://localhost:9000 `
                  -Dsonar.login=<squ_0f16c2b4162e8dc84bdd4f2d6e760d9679226518>
  displayName: 'Run SonarQube Analysis'
