trigger:
- main

pool:
  name: devops  # Replace with your Windows self-hosted agent pool name

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js 14'

- powershell: |
    cd backend
    npm install
  displayName: 'Install backend dependencies'

- powershell: |
    cd backend
    Start-Process npm -ArgumentList 'start' -NoNewWindow
    Start-Sleep -Seconds 5
    Invoke-WebRequest -Uri http://localhost:3000/ping -UseBasicParsing
  displayName: 'Start backend and test endpoint'

- powershell: |
    Write-Host "Frontend Files:"
    Get-ChildItem -Recurse frontend
  displayName: 'List frontend files'
